name: ultrack-i2k2024
channels:
  - gurobi
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - jupyterlab
  - jupytext
  - jupyterlab-myst
  - jupyter-book
  - notebook
  - cellpose
  - coin-or-cbc
  - gurobi
  - jupyter
  - nodejs
  - pip
  - pyqt
  - higra
  - pip:
    - py-ctcmetrics
    - napari
    - ultrack
