name: ultrack-i2k2024
channels:
  - gurobi
  - pytorch
  - funkelab
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - jupyterlab
  - jupytext
  - jupyterlab-myst
  - jupyter-book
  - notebook
  - postgresql
  - cellpose
  - coin-or-cbc
  - gurobi
  - ilpy
  - jupyter
  - nodejs
  - pip
  - higra
  - pip:
    - py-ctcmetrics
    - napari[all]
    - ultrack
    - napari-plot-profile
    - motile-plugin
